

services:
  web:
    build: .
    container_name: quicknotes_app
    ports:
      - "80:5000"  # Expose on EC2 public port 80
    volumes:
      - notes-data:/app/notes.db  # Named volume for DB persistence
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  notes-data:
